# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kamui < Formula
  desc "Command-line interface for Kamui Platform"
  homepage "https://kamui-platform.com"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kamui-project/cli/releases/download/v0.1.1/kamui_0.1.1_darwin_amd64.tar.gz"
      sha256 "686af4268d1cc020a3d53e02692cb2ff860b7f4f4a52f712635c39620a33b2b8"

      def install
        bin.install "kamui"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kamui-project/cli/releases/download/v0.1.1/kamui_0.1.1_darwin_arm64.tar.gz"
      sha256 "5c2d0e724108c9b32b51224a10f1ee5ee7a2c648b076b1434f2ffe24dbdc760b"

      def install
        bin.install "kamui"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kamui-project/cli/releases/download/v0.1.1/kamui_0.1.1_linux_amd64.tar.gz"
      sha256 "301e0a78f326bb5d3131eae0fe9da5172de8476060b43ae4e88e7a46744568ea"
      def install
        bin.install "kamui"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kamui-project/cli/releases/download/v0.1.1/kamui_0.1.1_linux_arm64.tar.gz"
      sha256 "83d4c26cd7f74e5f59ea9da98d9870594a8c3d02d31293a7834cb2c7ff3bb168"
      def install
        bin.install "kamui"
      end
    end
  end

  test do
    system "#{bin}/kamui", "--version"
  end
end
